version: "3"
services:
  excalidraw:
    build: .
    container_name: excalidraw-local
    ports:
      - "5000:5000"
    volumes:
      - excalidraw-data:/app/projects
    restart: unless-stopped

volumes:
  excalidraw-data:
